server.port: 8888
spring.application.name: config

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring.cloud.config.server.git:
  uri: https://github.com/SherryXRJ/test.git
  search-paths: /**

spring.cloud.config:
  label: dev
  username: username
  password: username

eureka:
  client:
    register-with-eureka: true

