server.port: 8090

spring:
  application:
    name: zuul-service

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true

zuul:
  ignoredServices: "*"
  routes:
    test_producer:
      path: /producer/**
      serviceId: test-producer




