# 定义3个profile 注册到2个注册中心
spring:
  profiles:
    active: producer1

---
spring:
  profiles: producer1
  application:
    name: test-producer
server:
  port: 7071

eureka:
  client:
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

---
spring:
  profiles: producer2
  application:
    name: test-producer

server:
  port: 7072

eureka:
  client:
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

---
spring:
  profiles: producer3
  application:
      name: test-producer
server:
  port: 7073

eureka:
  client:
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/